---
layout: default
title: "fastascan"
---

```fastascan``` is the name of a tool that we had to create in the MSc in bioinformatics as an assignment for a Unix/algorithmics course. This was one midterm assignment after approximately 2 months using bash. 

The purpose of this script is to design a tool that detects the .fa or .fasta files in an user-specified folder, does a summary of the files in the folder, and then an individual report containing the number of sequences, the number of amino acids/nucleotides in the whole file, specifying if the file is a symbolic link, and detecting if the file contains nucleotide or amino acid sequences. 

The user can specify the folder to search in, and also if they want the first and last "n" lines of the file to be shown. If the number of lines of the file is smaller than 2n, the whole file is shown. The format to use the tool is ```fastascan [folder] [number_of_lines]```. If the user doesn't specify the folder to search, it will use by default the current directory. If the user doesn't specify the number of lines, it won't show any content of the file. If the 1st argument is an integer, and there is no 2nd argument, it will interpret the 1st as the number of lines that the user wants to see, and will search in the current directory.

# Example

## Files
For an example, I created a folder with 4 different files (2 contain protein sequences in fasta format, 1 contains nucleic acid sequences in fasta format, and another one is a plain text without format). You can click them to see the content.

<details>
	
<summary>Click to toggle contents of cd40_seqs.fa</summary>
<pre>
<code>

>NM_134360.1 Rattus norvegicus CD40 molecule (Cd40), mRNA
CTGGCTGCTCTGATCTCGCTCTGCAATGCTGCCTTTGCCTCAGCTGTGCGCGCTCTGGGGCTGCTTGTTG
ACAGCGGTCCATCTAGGACAGTGTGTTACGTGCAGTGACAAACAGTACCTCCAAGGTGGCGAGTGCTGCG
ATTTGTGCCAGCCGGGAAACCGACTAGTTAGCCACTGCACAGCTCTTGAGAAGACCCAATGCCAACCGTG
CGACTCAGGCGAATTCTCAGCTCACTGGAACAGGGAGATCCGCTGCCACCAGCACCGACACTGCGAACTC
AATCAAGGGCTTCAGGTTAAGAAGGAGGGCACCGCGGTTTCAGACACTGTTTGTACCTGCAAGGAAGGGC
AGCACTGCGCCAGCAAGGAGTGCGAGACGTGCGCTCAGCACACGCCCTGTGGCCCTGGCTTTGGAGTCGT
GCAGATGGCCACTGAGACTACTGATACTGTCTGCCAACCCTGCCCGGTCGGATTCTTCTCCAATGGGTCA
TCACTTTTTGAAAAGTGTCATCCATGGACAAGCTGTGAAGATCAGAAGCTGATGGTCCTACGGGAAGGAA
CAAGTCAGACTGATACCCTCTGTGGTTTCCAGCCCCGGATGCGAGCCCTGCTGGTCATTCCCGTCGTGAT
GGTCATCCTCATCACCATCTTTGTGGTTTTTCTCTATATCAAAAAGGTGGTCAAGAAACCAAAGGACAAT
GAGGTCTTACCCCCTGAGGCTCGAGGACAAGATCCTGTGGAGATAGAAGATTATCCCGGTCACAACACTG
CTGCTCCAGTGCAGGAGACGTTGCATGGGTGTCAGCCTGTTGCACAGGAGGATGGTAAAGAGAGTCGCAT
CTCAGTGCAGGAGCGGCAGGTGACAGGCAGCATGGCCTTGAAGCCCCTGGTCTGAGCCCTGGAACTGTTT
TGGAGGTGATGGTTCCGGAGCAGGGGCCTGGCTCTGACAGCCGCTGACTTTTGAAGTTTGAGAGGAGCCA
AGGCAGAGCCCGGTGCAGCTAACTTTCGTGCCTGCCCCTGTCATCTCTCGACTTGCTTTTTAAAGATGGA
GGAAAAGCTTTGGCGTCAGGGGTCCGCAGTAATATCTACAGAGTGCAGCAATGCAGGCCCAGAGATGTCT
TGCTGCGGTTTTCACTGTAAGGAGTCGTGGACACGGGAGTCCATGACTTGTGGCTTGTGCTGCTAGAAGG
CACCTGGTTGCCCAGCAGCCGGGGACTGGCTAAATAAATCTGTAATTATTTAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA

>NM_001424339.1 Homo sapiens CD40 molecule (CD40), transcript variant 9, mRNA
AGTGGTCCTGCCGCCTGGTCTCACCTCGCTATGGTTCGTCTGCCTCTGCAGTGCGTCCTCTGGGGCTGCT
TGCTGACCGCTGTCCATCCAGAACCACCCACTGCATGCAGAGAAAAACAGTACCTAATAAACAGTCAGTG
CTGTTCTTTGTGCCAGCCAGGACAGAAACTGGTGAGTGACTGCACAGAGTTCACTGAAACGGAATGCCTT
CCTTGCGGTGAAAGCGAATTCCTAGACACCTGGAACAGAGAGACACACTGCCACCAGCACAAATACTGCG
ACCCCAACCTAGGGCTTCGGGTCCAGCAGAAGGGCACCTCAGAAACAGACACCATCTGCACCTGTGAAGA
AGGCTGGCACTGTACGAGTGAGGCCTGTGAGAGCTGTGTCCTGCACCGCTCATGCTCGCCCGGCTTTGGG
GTCAAGCAGATTGGTCCCCAGGATCGGCTGAGAGCCCTGGTGGTGATCCCCATCATCTTCGGGATCCTGT
TTGCCATCCTCTTGGTGCTGGTCTTTATCAGTGAGTCCTCAGAAAAGGTGGCCAAGAAGCCAACCAATAA
GGCCCCCCACCCCAAGCAGGAACCCCAGGAGATCAATTTTCCCGACGATCTTCCTGGCTCCAACACTGCT
GCTCCAGTGCAGGAGACTTTACATGGATGCCAACCGGTCACCCAGGAGGATGGCAAAGAGAGTCGCATCT
CAGTGCAGGAGAGACAGTGAGGCTGCACCCACCCAGGAGTGTGGCCACGTGGGCAAACAGGCAGTTGGCC
AGAGAGCCTGGTGCTGCTGCTGCTGTGGCGTGAGGGTGAGGGGCTGGCACTGACTGGGCATAGCTCCCCG
CTTCTGCCTGCACCCCTGCAGTTTGAGACAGGAGACCTGGCACTGGATGCAGAAACAGTTCACCTTGAAG
AACCTCTCACTTCACCCTGGAGCCCATCCAGTCTCCCAACTTGTATTAAAGACAGAGGCAGAAGTTTGGT
GGTGGTGGTGTTGGGGTATGGTTTAGTAATATCCACCAGACCTTCCGATCCAGCAGTTTGGTGCCCAGAG
AGGCATCATGGTGGCTTCCCTGCGCCCAGGAAGCCATATACACAGATGCCCATTGCAGCATTGTTTGTGA
TAGTGAACAACTGGAAGCTGCTTAACTGTCCATCAGCAGGAGACTGGCTAAATAAAATTAGAATATATTT
ATACAACAGAATCTCAAAAACACTGTTGAGTAAGGAAAAAAAGGCATGCTGCTGAATGATGGGTATGGAA
CTTTTTAAAAAAGTACATGCTTTTATGTATGTATATTGCCTATGGATATATGTATAAATACAATATGCAT
CATATATTGATATAACAAGGGTTCTGGAAGGGTACACAGAAAACCCACAGCTCGAAGAGTGGTGACGTCT
GGGGTGGGGAAGAAGGGTCTGGGGGAGGGTTGGTTAAAGGGAGATTTGGCTTTCCCATAATGCTTCATCA
TTTTTCCCAAAAGGAGAGTGAATTCACATAATGCTTATGTAATTAAAAAATCATCAAACATGTAAAAA

>NM_001322421.2 Homo sapiens CD40 molecule (CD40), transcript variant 5, mRNA
AGTGGTCCTGCCGCCTGGTCTCACCTCGCTATGGTTCGTCTGCCTCTGCAGTGCGTCCTCTGGGGCTGCT
TGCTGACCGCTGTCCATCCAGAACCACCCACTGCATGCAGAGAAAAACAGTACCTAATAAACAGTCAGTG
CTGTTCTTTGTGCCAGCCAGGACAGAAACTGGTGAGTGACTGCACAGAGTTCACTGAAACGGAATGCCTT
CCTTGCGGTGAAAGCGAATTCCTAGACACCTGGAACAGAGAGACACACTGCCACCAGCACAAATACTGCG
ACCCCAACCTAGGGCTTCGGGTCCAGCAGAAGGGCACCTCAGAAACAGACACCATCTGCACCTGTGAAGA
AGGCTGGCACTGTACGAGTGAGGCCTGTGAGAGCTGTGTCCTGCACCGCTCATGCTCGCCCGGCTTTGGG
GTCAAGCAGATTGCTACAGGGGTTTCTGATACCATCTGCGAGCCCTGCCCAGTCGGCTTCTTCTCCAATG
TGTCATCTGCTTTCGAAAAATGTCACCCTTGGACAAGCTGTGAGACCAAAGACCTGGTTGTGCAACAGGC
AGGCACAAACAAGACTGATGTTGTCTGTGGTCCCCAGGATCGGCTGAGAGCCCTGGTGGTGATCCCCATC
ATCTTCGGGATCCTGTTTGCCATCCTCTTGGTGCTGGTCTTTATCAGTGAGTCCTCAGAAAAGGTGGCCA
AGAAGCCAACCAATAAGGCCCCCCACCCCAAGCAGGAACCCCAGGAGATCAATTTTCCCGACGATCTTCC
TGGCTCCAACACTGCTGCTCCAGTGCAGGAGACTTTACATGGATGCCAACCGGTCACCCAGGAGGATGGC
AAAGAGAGTCGCATCTCAGTGCAGGAGAGACAGTGAGGCTGCACCCACCCAGGAGTGTGGCCACGTGGGC
AAACAGGCAGTTGGCCAGAGAGCCTGGTGCTGCTGCTGCTGTGGCGTGAGGGTGAGGGGCTGGCACTGAC
TGGGCATAGCTCCCCGCTTCTGCCTGCACCCCTGCAGTTTGAGACAGGAGACCTGGCACTGGATGCAGAA
ACAGTTCACCTTGAAGAACCTCTCACTTCACCCTGGAGCCCATCCAGTCTCCCAACTTGTATTAAAGACA
GAGGCAGAAGTTTGGTGGTGGTGGTGTTGGGGTATGGTTTAGTAATATCCACCAGACCTTCCGATCCAGC
AGTTTGGTGCCCAGAGAGGCATCATGGTGGCTTCCCTGCGCCCAGGAAGCCATATACACAGATGCCCATT
GCAGCATTGTTTGTGATAGTGAACAACTGGAAGCTGCTTAACTGTCCATCAGCAGGAGACTGGCTAAATA
AAATTAGAATATATTTATACAACAGAATCTCAAAAACACTGTTGAGTAAGGAAAAAAAGGCATGCTGCTG
AATGATGGGTATGGAACTTTTTAAAAAAGTACATGCTTTTATGTATGTATATTGCCTATGGATATATGTA
TAAATACAATATGCATCATATATTGATATAACAAGGGTTCTGGAAGGGTACACAGAAAACCCACAGCTCG
AAGAGTGGTGACGTCTGGGGTGGGGAAGAAGGGTCTGGGGGAGGGTTGGTTAAAGGGAGATTTGGCTTTC
CCATAATGCTTCATCATTTTTCCCAAAAGGAGAGTGAATTCACATAATGCTTATGTAATTAAAAAATCAT
CAAACATGTAAAAA

>NM_152854.4 Homo sapiens CD40 molecule (CD40), transcript variant 2, mRNA
AGTGGTCCTGCCGCCTGGTCTCACCTCGCTATGGTTCGTCTGCCTCTGCAGTGCGTCCTCTGGGGCTGCT
TGCTGACCGCTGTCCATCCAGAACCACCCACTGCATGCAGAGAAAAACAGTACCTAATAAACAGTCAGTG
CTGTTCTTTGTGCCAGCCAGGACAGAAACTGGTGAGTGACTGCACAGAGTTCACTGAAACGGAATGCCTT
CCTTGCGGTGAAAGCGAATTCCTAGACACCTGGAACAGAGAGACACACTGCCACCAGCACAAATACTGCG
ACCCCAACCTAGGGCTTCGGGTCCAGCAGAAGGGCACCTCAGAAACAGACACCATCTGCACCTGTGAAGA
AGGCTGGCACTGTACGAGTGAGGCCTGTGAGAGCTGTGTCCTGCACCGCTCATGCTCGCCCGGCTTTGGG
GTCAAGCAGATTGCTACAGGGGTTTCTGATACCATCTGCGAGCCCTGCCCAGTCGGCTTCTTCTCCAATG
TGTCATCTGCTTTCGAAAAATGTCACCCTTGGACAAGGTCCCCAGGATCGGCTGAGAGCCCTGGTGGTGA
TCCCCATCATCTTCGGGATCCTGTTTGCCATCCTCTTGGTGCTGGTCTTTATCAAAAAGGTGGCCAAGAA
GCCAACCAATAAGGCCCCCCACCCCAAGCAGGAACCCCAGGAGATCAATTTTCCCGACGATCTTCCTGGC
TCCAACACTGCTGCTCCAGTGCAGGAGACTTTACATGGATGCCAACCGGTCACCCAGGAGGATGGCAAAG
AGAGTCGCATCTCAGTGCAGGAGAGACAGTGAGGCTGCACCCACCCAGGAGTGTGGCCACGTGGGCAAAC
AGGCAGTTGGCCAGAGAGCCTGGTGCTGCTGCTGCTGTGGCGTGAGGGTGAGGGGCTGGCACTGACTGGG
CATAGCTCCCCGCTTCTGCCTGCACCCCTGCAGTTTGAGACAGGAGACCTGGCACTGGATGCAGAAACAG
TTCACCTTGAAGAACCTCTCACTTCACCCTGGAGCCCATCCAGTCTCCCAACTTGTATTAAAGACAGAGG
CAGAAGTTTGGTGGTGGTGGTGTTGGGGTATGGTTTAGTAATATCCACCAGACCTTCCGATCCAGCAGTT
TGGTGCCCAGAGAGGCATCATGGTGGCTTCCCTGCGCCCAGGAAGCCATATACACAGATGCCCATTGCAG
CATTGTTTGTGATAGTGAACAACTGGAAGCTGCTTAACTGTCCATCAGCAGGAGACTGGCTAAATAAAAT
TAGAATATATTTATACAACAGAATCTCAAAAACACTGTTGAGTAAGGAAAAAAAGGCATGCTGCTGAATG
ATGGGTATGGAACTTTTTAAAAAAGTACATGCTTTTATGTATGTATATTGCCTATGGATATATGTATAAA
TACAATATGCATCATATATTGATATAACAAGGGTTCTGGAAGGGTACACAGAAAACCCACAGCTCGAAGA
GTGGTGACGTCTGGGGTGGGGAAGAAGGGTCTGGGGGAGGGTTGGTTAAAGGGAGATTTGGCTTTCCCAT
AATGCTTCATCATTTTTCCCAAAAGGAGAGTGAATTCACATAATGCTTATGTAATTAAAAAATCATCAAA
CATGTAAAAA

>NM_001322422.2 Homo sapiens CD40 molecule (CD40), transcript variant 6, mRNA
AGTGGTCCTGCCGCCTGGTCTCACCTCGCTATGGTTCGTCTGCCTCTGCAGTGCGTCCTCTGGGGCTGCT
TGCTGACCGCTGTCCATCCAGAACCACCCACTGCATGCAGAGAAAAACAGTACCTAATAAACAGTCAGTG
CTGTTCTTTGTGCCAGCCAGGACAGAAACTGGTGAGTGACTGCACAGAGTTCACTGAAACGGAATGCCTT
CCTTGCGGTGAAAGCGAATTCCTAGACACCTGGAACAGAGAGACACACTGCCACCAGCACAAATACTGCG
ACCCCAACCTAGGGCTTCGGGTCCAGCAGAAGGGCACCTCAGAAACAGACACCATCTGCACCTGTGAAGA
AGGCTGGCACTGTACGAGTGAGGCCTGTGAGAGCTGTGTCCTGCACCGCTCATGCTCGCCCGGCTTTGGG
GTCAAGCAGATTGGTCCCCAGGATCGGCTGAGAGCCCTGGTGGTGATCCCCATCATCTTCGGGATCCTGT
TTGCCATCCTCTTGGTGCTGGTCTTTATCAAAAAGGTGGCCAAGAAGCCAACCAATAAGGCCCCCCACCC
CAAGCAGGAACCCCAGGAGATCAATTTTCCCGACGATCTTCCTGGCTCCAACACTGCTGCTCCAGTGCAG
GAGACTTTACATGGATGCCAACCGGTCACCCAGGAGGATGGCAAAGAGAGTCGCATCTCAGTGCAGGAGA
GACAGTGAGGCTGCACCCACCCAGGAGTGTGGCCACGTGGGCAAACAGGCAGTTGGCCAGAGAGCCTGGT
GCTGCTGCTGCTGTGGCGTGAGGGTGAGGGGCTGGCACTGACTGGGCATAGCTCCCCGCTTCTGCCTGCA
CCCCTGCAGTTTGAGACAGGAGACCTGGCACTGGATGCAGAAACAGTTCACCTTGAAGAACCTCTCACTT
CACCCTGGAGCCCATCCAGTCTCCCAACTTGTATTAAAGACAGAGGCAGAAGTTTGGTGGTGGTGGTGTT
GGGGTATGGTTTAGTAATATCCACCAGACCTTCCGATCCAGCAGTTTGGTGCCCAGAGAGGCATCATGGT
GGCTTCCCTGCGCCCAGGAAGCCATATACACAGATGCCCATTGCAGCATTGTTTGTGATAGTGAACAACT
GGAAGCTGCTTAACTGTCCATCAGCAGGAGACTGGCTAAATAAAATTAGAATATATTTATACAACAGAAT
CTCAAAAACACTGTTGAGTAAGGAAAAAAAGGCATGCTGCTGAATGATGGGTATGGAACTTTTTAAAAAA
GTACATGCTTTTATGTATGTATATTGCCTATGGATATATGTATAAATACAATATGCATCATATATTGATA
TAACAAGGGTTCTGGAAGGGTACACAGAAAACCCACAGCTCGAAGAGTGGTGACGTCTGGGGTGGGGAAG
AAGGGTCTGGGGGAGGGTTGGTTAAAGGGAGATTTGGCTTTCCCATAATGCTTCATCATTTTTCCCAAAA
GGAGAGTGAATTCACATAATGCTTATGTAATTAAAAAATCATCAAACATGTAAAAA

>NM_001362758.2 Homo sapiens CD40 molecule (CD40), transcript variant 8, mRNA
AGTGGTCCTGCCGCCTGGTCTCACCTCGCTATGGTTCGTCTGCCTCTGCAGTGCGTCCTCTGGGGCTGCT
TGCTGACCGCTGTCCATCCAGAACCACCCACTGCATGCAGAGAAAAACAGTACCTAATAAACAGTCAGTG
CTGTTCTTTGTGCCAGCCAGGACAGAAACTGGTGAGTGACTGCACAGAGTTCACTGAAACGGAATGCCTT
CCTTGCGGTGAAAGCGAATTCCTAGACACCTGGAACAGAGAGACACACTGCCACCAGCACAAATACTGCG
ACCCCAACCTAGGGCTTCGGGTCCAGCAGAAGGGCACCTCAGAAACAGACACCATCTGCACCTGTGAAGA
AGGCTGGCACTGTACGAGTGAGGCCTGTGAGAGCTGTGTCCTGCACCGCTCATGCTCGCCCGGCTTTGGG
GTCAAGCAGATTGCTACAGGGGTTTCTGATACCATCTGCGAGCCCTGCCCAGTCGGCTTCTTCTCCAATG
TGTCATCTGCTTTCGAAAAATGTCACCCTTGGACAAGCTGTGAGACCAAAGACCTGGTTGTGCAACAGGC
AGGCACAAACAAGACTGATGTTGTCTGTGGTCCCCAGGATCGGCTGAGAGCCCTGGTGGTGATCCCCATC
ATCTTCGGGATCCTGTTTGCCATCCTCTTGGTGCTGGTCTTTATCAGTGGCCAAGAAGCCAACCAATAAG
GCCCCCCACCCCAAGCAGGAACCCCAGGAGATCAATTTTCCCGACGATCTTCCTGGCTCCAACACTGCTG
CTCCAGTGCAGGAGACTTTACATGGATGCCAACCGGTCACCCAGGAGGATGGCAAAGAGAGTCGCATCTC
AGTGCAGGAGAGACAGTGAGGCTGCACCCACCCAGGAGTGTGGCCACGTGGGCAAACAGGCAGTTGGCCA
GAGAGCCTGGTGCTGCTGCTGCTGTGGCGTGAGGGTGAGGGGCTGGCACTGACTGGGCATAGCTCCCCGC
TTCTGCCTGCACCCCTGCAGTTTGAGACAGGAGACCTGGCACTGGATGCAGAAACAGTTCACCTTGAAGA
ACCTCTCACTTCACCCTGGAGCCCATCCAGTCTCCCAACTTGTATTAAAGACAGAGGCAGAAGTTTGGTG
GTGGTGGTGTTGGGGTATGGTTTAGTAATATCCACCAGACCTTCCGATCCAGCAGTTTGGTGCCCAGAGA
GGCATCATGGTGGCTTCCCTGCGCCCAGGAAGCCATATACACAGATGCCCATTGCAGCATTGTTTGTGAT
AGTGAACAACTGGAAGCTGCTTAACTGTCCATCAGCAGGAGACTGGCTAAATAAAATTAGAATATATTTA
TACAACAGAATCTCAAAAACACTGTTGAGTAAGGAAAAAAAGGCATGCTGCTGAATGATGGGTATGGAAC
TTTTTAAAAAAGTACATGCTTTTATGTATGTATATTGCCTATGGATATATGTATAAATACAATATGCATC
ATATATTGATATAACAAGGGTTCTGGAAGGGTACACAGAAAACCCACAGCTCGAAGAGTGGTGACGTCTG
GGGTGGGGAAGAAGGGTCTGGGGGAGGGTTGGTTAAAGGGAGATTTGGCTTTCCCATAATGCTTCATCAT
TTTTCCCAAAAGGAGAGTGAATTCACATAATGCTTATGTAATTAAAAAATCATCAAACATGTAAAAA

>NM_001302753.2 Homo sapiens CD40 molecule (CD40), transcript variant 3, mRNA
AGTGGTCCTGCCGCCTGGTCTCACCTCGCTATGGTTCGTCTGCCTCTGCAGTGCGTCCTCTGGGGCTGCT
TGCTGACCGCTGTCCATCCAGAACCACCCACTGCATGCAGAGAAAAACAGTACCTAATAAACAGTCAGTG
CTGTTCTTTGTGCCAGCCAGGACAGAAACTGGTGAGTGACTGCACAGAGTTCACTGAAACGGAATGCCTT
CCTTGCGGTGAAAGCGAATTCCTAGACACCTGGAACAGAGAGACACACTGCCACCAGCACAAATACTGCG
ACCCCAACCTAGGGCTTCGGGTCCAGCAGAAGGGCACCTCAGAAACAGACACCATCTGCACCTGTGAAGA
AGGCTGGCACTGTACGAGTGAGGCCTGTGAGAGCTGTGTCCTGCACCGCTCATGCTCGCCCGGCTTTGGG
GTCAAGCAGATTGCTACAGGGGTTTCTGATACCATCTGCGAGCCCTGCCCAGTCGGCTTCTTCTCCAATG
TGTCATCTGCTTTCGAAAAATGTCACCCTTGGACAAGCTGTGAGACCAAAGACCTGGTTGTGCAACAGGC
AGGCACAAACAAGACTGATGTTGTCTGTGGTGAGTCCTGGACAATGGGCCCTGGAGAAAGCCTAGGAAGG
TCCCCAGGATCGGCTGAGAGCCCTGGTGGTGATCCCCATCATCTTCGGGATCCTGTTTGCCATCCTCTTG
GTGCTGGTCTTTATCAAAAAGGTGGCCAAGAAGCCAACCAATAAGGCCCCCCACCCCAAGCAGGAACCCC
AGGAGATCAATTTTCCCGACGATCTTCCTGGCTCCAACACTGCTGCTCCAGTGCAGGAGACTTTACATGG
ATGCCAACCGGTCACCCAGGAGGATGGCAAAGAGAGTCGCATCTCAGTGCAGGAGAGACAGTGAGGCTGC
ACCCACCCAGGAGTGTGGCCACGTGGGCAAACAGGCAGTTGGCCAGAGAGCCTGGTGCTGCTGCTGCTGT
GGCGTGAGGGTGAGGGGCTGGCACTGACTGGGCATAGCTCCCCGCTTCTGCCTGCACCCCTGCAGTTTGA
GACAGGAGACCTGGCACTGGATGCAGAAACAGTTCACCTTGAAGAACCTCTCACTTCACCCTGGAGCCCA
TCCAGTCTCCCAACTTGTATTAAAGACAGAGGCAGAAGTTTGGTGGTGGTGGTGTTGGGGTATGGTTTAG
TAATATCCACCAGACCTTCCGATCCAGCAGTTTGGTGCCCAGAGAGGCATCATGGTGGCTTCCCTGCGCC
CAGGAAGCCATATACACAGATGCCCATTGCAGCATTGTTTGTGATAGTGAACAACTGGAAGCTGCTTAAC
TGTCCATCAGCAGGAGACTGGCTAAATAAAATTAGAATATATTTATACAACAGAATCTCAAAAACACTGT
TGAGTAAGGAAAAAAAGGCATGCTGCTGAATGATGGGTATGGAACTTTTTAAAAAAGTACATGCTTTTAT
GTATGTATATTGCCTATGGATATATGTATAAATACAATATGCATCATATATTGATATAACAAGGGTTCTG
GAAGGGTACACAGAAAACCCACAGCTCGAAGAGTGGTGACGTCTGGGGTGGGGAAGAAGGGTCTGGGGGA
GGGTTGGTTAAAGGGAGATTTGGCTTTCCCATAATGCTTCATCATTTTTCCCAAAAGGAGAGTGAATTCA
CATAATGCTTATGTAATTAAAAAATCATCAAACATGTAAAAA

>NM_001250.6 Homo sapiens CD40 molecule (CD40), transcript variant 1, mRNA
AGTGGTCCTGCCGCCTGGTCTCACCTCGCTATGGTTCGTCTGCCTCTGCAGTGCGTCCTCTGGGGCTGCT
TGCTGACCGCTGTCCATCCAGAACCACCCACTGCATGCAGAGAAAAACAGTACCTAATAAACAGTCAGTG
CTGTTCTTTGTGCCAGCCAGGACAGAAACTGGTGAGTGACTGCACAGAGTTCACTGAAACGGAATGCCTT
CCTTGCGGTGAAAGCGAATTCCTAGACACCTGGAACAGAGAGACACACTGCCACCAGCACAAATACTGCG
ACCCCAACCTAGGGCTTCGGGTCCAGCAGAAGGGCACCTCAGAAACAGACACCATCTGCACCTGTGAAGA
AGGCTGGCACTGTACGAGTGAGGCCTGTGAGAGCTGTGTCCTGCACCGCTCATGCTCGCCCGGCTTTGGG
GTCAAGCAGATTGCTACAGGGGTTTCTGATACCATCTGCGAGCCCTGCCCAGTCGGCTTCTTCTCCAATG
TGTCATCTGCTTTCGAAAAATGTCACCCTTGGACAAGCTGTGAGACCAAAGACCTGGTTGTGCAACAGGC
AGGCACAAACAAGACTGATGTTGTCTGTGGTCCCCAGGATCGGCTGAGAGCCCTGGTGGTGATCCCCATC
ATCTTCGGGATCCTGTTTGCCATCCTCTTGGTGCTGGTCTTTATCAAAAAGGTGGCCAAGAAGCCAACCA
ATAAGGCCCCCCACCCCAAGCAGGAACCCCAGGAGATCAATTTTCCCGACGATCTTCCTGGCTCCAACAC
TGCTGCTCCAGTGCAGGAGACTTTACATGGATGCCAACCGGTCACCCAGGAGGATGGCAAAGAGAGTCGC
ATCTCAGTGCAGGAGAGACAGTGAGGCTGCACCCACCCAGGAGTGTGGCCACGTGGGCAAACAGGCAGTT
GGCCAGAGAGCCTGGTGCTGCTGCTGCTGTGGCGTGAGGGTGAGGGGCTGGCACTGACTGGGCATAGCTC
CCCGCTTCTGCCTGCACCCCTGCAGTTTGAGACAGGAGACCTGGCACTGGATGCAGAAACAGTTCACCTT
GAAGAACCTCTCACTTCACCCTGGAGCCCATCCAGTCTCCCAACTTGTATTAAAGACAGAGGCAGAAGTT
TGGTGGTGGTGGTGTTGGGGTATGGTTTAGTAATATCCACCAGACCTTCCGATCCAGCAGTTTGGTGCCC
AGAGAGGCATCATGGTGGCTTCCCTGCGCCCAGGAAGCCATATACACAGATGCCCATTGCAGCATTGTTT
GTGATAGTGAACAACTGGAAGCTGCTTAACTGTCCATCAGCAGGAGACTGGCTAAATAAAATTAGAATAT
ATTTATACAACAGAATCTCAAAAACACTGTTGAGTAAGGAAAAAAAGGCATGCTGCTGAATGATGGGTAT
GGAACTTTTTAAAAAAGTACATGCTTTTATGTATGTATATTGCCTATGGATATATGTATAAATACAATAT
GCATCATATATTGATATAACAAGGGTTCTGGAAGGGTACACAGAAAACCCACAGCTCGAAGAGTGGTGAC
GTCTGGGGTGGGGAAGAAGGGTCTGGGGGAGGGTTGGTTAAAGGGAGATTTGGCTTTCCCATAATGCTTC
ATCATTTTTCCCAAAAGGAGAGTGAATTCACATAATGCTTATGTAATTAAAAAATCATCAAACATGTAAA
AA
</code>
</pre>
</details>

<details>
<summary>Click to toggle contents of normal_text.txt</summary>
<pre>
<code>
hello this is an example text
hello hello hello 
hello this is an example text
</code>
</pre>

</details>


<details>
	
<summary>Click to toggle contents of Q9NZQ7.fasta</summary>
<pre>
<code>
>sp|Q9NZQ7|PD1L1_HUMAN Programmed cell death 1 ligand 1 OS=Homo sapiens OX=9606 GN=CD274 PE=1 SV=1
MRIFAVFIFMTYWHLLNAFTVTVPKDLYVVEYGSNMTIECKFPVEKQLDLAALIVYWEME
DKNIIQFVHGEEDLKVQHSSYRQRARLLKDQLSLGNAALQITDVKLQDAGVYRCMISYGG
ADYKRITVKVNAPYNKINQRILVVDPVTSEHELTCQAEGYPKAEVIWTSSDHQVLSGKTT
TTNSKREEKLFNVTSTLRINTTTNEIFYCTFRRLDPEENHTAELVIPELPLAHPPNERTH
LVILGAILLCLGVALTFIFRLRKGRMMDVKKCGIQDTNSKKQSDTHLEET
</code>
</pre>



</details>


<details>
	
<summary>Click to toggle contents of Q9Y4U1.fasta</summary>
<pre>
<code>
>sp|Q9Y4U1|MMAC_HUMAN Cyanocobalamin reductase / alkylcobalamin dealkylase OS=Homo sapiens OX=9606 GN=MMACHC PE=1 SV=3
MEPKVAELKQKIEDTLCPFGFEVYPFQVAWYNELLPPAFHLPLPGPTLAFLVLSTPAMFD
RALKPFLQSCHLRMLTDPVDQCVAYHLGRVRESLPELQIEIIADYEVHPNRRPKILAQTA
AHVAGAAYYYQRQDVEADPWGNQRISGVCIHPRFGGWFAIRGVVLLPGIEVPDLPPRKPH
DCVPTRADRIALLEGFNFHWRDWTYRDAVTPQERYSEEQKAYFSTPPAQRLALLGLAQPS
EKPSSPSPDLPFTTPAPKKPGNPSRARSWLSPRVSPPASPGP
</code>
</pre>

</details>


## Output

This is the output of ```fastascan``` using the default settings (without specifying directory or number of lines, meaning that it will search in the current directory and not show any content from the files):

<details>
	
<summary>Click to toggle the output</summary>
<pre>
<code>

suarezalvarezðŸ‰ ~/sequences_example $ fastascan

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!IMPORTANT INFORMATION!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
This program uses 2 arguments: the directory and the number of lines of each file to show.
If you only specify one of them, it will be interpreted as the number of lines if this argument is an integer, and as the directory if it is a text string.

This program considers a .fasta or .fa file to be a nucleotide (RNA or DNA) sequence if the content of A, C, T, G, U and N (upper or lower case) in the sequences contained in the file is greater or equal than 90%. If this condition is not fulfilled, the file will automatically be considered a protein sequence file.

This program considers the first word (delimited by spaces) after the ">" symbol in a fasta header as the identifier of the sequence.

================================================================
======================== SUMMARY ===============================
================================================================

Total number of .fasta and .fa files in the specified folders and its subfolders: 3
Number of unique fasta IDs: 10


================================================================
================== INDIVIDUAL REPORT ===========================
================================================================


========== /home/martin/sequences_example/Q9Y4U1.fasta [PROTEIN FASTA FILE] ==========
xx 1 protein sequence(s)
xx 282 amino acids in the sequences of this file
xx Not a symbolic link


========== /home/martin/sequences_example/cd40_seqs.fa [NUCLEIC ACID FASTA FILE] ==========
xx 8 nucleic acid sequence(s)
xx 12731 nucleotides in the sequences of this file
xx Not a symbolic link


========== /home/martin/sequences_example/Q9NZQ7.fasta [PROTEIN FASTA FILE] ==========
xx 1 protein sequence(s)
xx 290 amino acids in the sequences of this file
xx Not a symbolic link
```
</code>
</pre>
</details>


And this is the output specifying the folder from my home folder, and specifying the number of lines. 

<details>
	
<summary>Click to toggle the output</summary>
<pre>
<code>
suarezalvarezðŸ‰ ~ $ fastascan sequences_example/ 4

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!IMPORTANT INFORMATION!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
This program uses 2 arguments: the directory and the number of lines of each file to show.
If you only specify one of them, it will be interpreted as the number of lines if this argument is an integer, and as the directory if it is a text string.

This program considers a .fasta or .fa file to be a nucleotide (RNA or DNA) sequence if the content of A, C, T, G, U and N (upper or lower case) in the sequences contained in the file is greater or equal than 90%. If this condition is not fulfilled, the file will automatically be considered a protein sequence file.

This program considers the first word (delimited by spaces) after the ">" symbol in a fasta header as the identifier of the sequence.

================================================================
======================== SUMMARY ===============================
================================================================

Total number of .fasta and .fa files in the specified folders and its subfolders: 3
Number of unique fasta IDs: 10


================================================================
================== INDIVIDUAL REPORT ===========================
================================================================


========== sequences_example/Q9Y4U1.fasta [PROTEIN FASTA FILE] ==========
xx 1 protein sequence(s)
xx 282 amino acids in the sequences of this file
xx Not a symbolic link


-- previsualization of the file content--

>sp|Q9Y4U1|MMAC_HUMAN Cyanocobalamin reductase / alkylcobalamin dealkylase OS=Homo sapiens OX=9606 GN=MMACHC PE=1 SV=3
MEPKVAELKQKIEDTLCPFGFEVYPFQVAWYNELLPPAFHLPLPGPTLAFLVLSTPAMFD
RALKPFLQSCHLRMLTDPVDQCVAYHLGRVRESLPELQIEIIADYEVHPNRRPKILAQTA
AHVAGAAYYYQRQDVEADPWGNQRISGVCIHPRFGGWFAIRGVVLLPGIEVPDLPPRKPH
DCVPTRADRIALLEGFNFHWRDWTYRDAVTPQERYSEEQKAYFSTPPAQRLALLGLAQPS
EKPSSPSPDLPFTTPAPKKPGNPSRARSWLSPRVSPPASPGP

========== sequences_example/cd40_seqs.fa [NUCLEIC ACID FASTA FILE] ==========
xx 8 nucleic acid sequence(s)
xx 12731 nucleotides in the sequences of this file
xx Not a symbolic link


-- previsualization of the file content --

[!!!]WARNING: Only the first and last 4 lines are printed[!!!]

>NM_134360.1 Rattus norvegicus CD40 molecule (Cd40), mRNA
CTGGCTGCTCTGATCTCGCTCTGCAATGCTGCCTTTGCCTCAGCTGTGCGCGCTCTGGGGCTGCTTGTTG
ACAGCGGTCCATCTAGGACAGTGTGTTACGTGCAGTGACAAACAGTACCTCCAAGGTGGCGAGTGCTGCG
ATTTGTGCCAGCCGGGAAACCGACTAGTTAGCCACTGCACAGCTCTTGAGAAGACCCAATGCCAACCGTG
...
GTCTGGGGTGGGGAAGAAGGGTCTGGGGGAGGGTTGGTTAAAGGGAGATTTGGCTTTCCCATAATGCTTC
ATCATTTTTCCCAAAAGGAGAGTGAATTCACATAATGCTTATGTAATTAAAAAATCATCAAACATGTAAA
AA


========== sequences_example/Q9NZQ7.fasta [PROTEIN FASTA FILE] ==========
xx 1 protein sequence(s)
xx 290 amino acids in the sequences of this file
xx Not a symbolic link


-- previsualization of the file content--

>sp|Q9NZQ7|PD1L1_HUMAN Programmed cell death 1 ligand 1 OS=Homo sapiens OX=9606 GN=CD274 PE=1 SV=1
MRIFAVFIFMTYWHLLNAFTVTVPKDLYVVEYGSNMTIECKFPVEKQLDLAALIVYWEME
DKNIIQFVHGEEDLKVQHSSYRQRARLLKDQLSLGNAALQITDVKLQDAGVYRCMISYGG
ADYKRITVKVNAPYNKINQRILVVDPVTSEHELTCQAEGYPKAEVIWTSSDHQVLSGKTT
TTNSKREEKLFNVTSTLRINTTTNEIFYCTFRRLDPEENHTAELVIPELPLAHPPNERTH
LVILGAILLCLGVALTFIFRLRKGRMMDVKKCGIQDTNSKKQSDTHLEET
</code>
</pre>

</details>


# Code


<h3><a href="https://github.com/suarezalvarez/peekfile/blob/main/fastascan.sh">Check the code here</a><h3>



